format:
  html: {toc: true, toc-depth: 4, theme: spacelab}
  revealjs: {theme: solarized, navigation-mode: vertical, transition: slide, background-transition: fade, incremental: true}
project: {type: book}
book:
  title: Using ONNX models from clojure
  chapters: [index.qmd, onnx.qmd]
