project:
  type: book

format:
  html:
    theme: cosmo

book:
  title: "Clojure Data Scrapbook"
  chapters:
    - index.qmd
    - copies_of_projects/main/docs/scicloj/scrapbook/python_quarto.qmd
    - copies_of_projects/main/docs/scicloj/scrapbook/visualization_quarto.qmd
    - copies_of_projects/main/docs/scicloj/scrapbook/tests_quarto.qmd
    - copies_of_projects/hdf/docs/scicloj/scrapbook/hdf_quarto.qmd
