name: Build tutorials page

on:
  - push

permissions:
  contents: read
  pages: write
  id-token: write
  packages: write
  
jobs:


  render-tutorials:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    
    - name: install devcontainer-cli
      run:  npm install -g @devcontainers/cli

    - name: install devcontainer-cli
      run:  devcontainer -h

    - name: run devcontainer build
      run: |
         devcontainer up --workspace-folder projects/noj
         devcontainer exec --workspace-folder projects/noj clj notebooks/render.clj
    

    - name: combine all tutorials
      uses: tzafrirben/babashka-docker-action@v1.1
      with:
         bb_src: make_docs.clj


    - name: Prepare java
      uses: actions/setup-java@v3
      with:
          distribution: 'zulu'
          java-version: '8'

    - name: Install clojure tools
      uses: DeLaGuardo/setup-clojure@12.5
      with:
          cli: 1.10.1.693 

    - name: fix permisions
      run: sudo chmod o+w docs/

      
    - name: create main index
      run: clojure notebooks/render_index.clj 


    - name: Setup Pages
      uses: actions/configure-pages@v5
    - name: Build with Jekyll
      uses: actions/jekyll-build-pages@v1
      with:
         source: ./docs
         destination: ./_site
    
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
    
  deploy-pages:
   environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
   runs-on: ubuntu-latest
   # only run github-pages deployemnts on main, not on PRs for example
   if: github.ref == 'refs/heads/main'
   needs: render-tutorials
   steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
