name: Clojure CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  render-tutorials:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: render tutorial in projects/noj
      uses: devcontainers/ci@v0.3
      with:    
               subFolder: projects/noj
               push: never
               runCmd: clj notebooks/render.clj

    - name: render tutorial in projects/data-processing
      uses: devcontainers/ci@v0.3
      with:    
               subFolder: projects/data-processing
               push: never
               runCmd: clj notebooks/render.clj

               


    - name: combine all tutorials
      uses: tzafrirben/babashka-docker-action@v1.1
      with:
         bb_src: make_docs.clj
                         
